spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/stonemark}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/stonemark/protocol/openid-connect/certs}

application:
  security:
    action-code:
      email-verification:
        expiration: 86400000 # 24 hours
      password-reset:
        expiration: 3600000 # 1 hour
      two-factor:
        expiration: 3600000 # 1 hour
      telephone-verification:
        expiration: 900000 # 15 minutes
      device-verification:
        expiration: 2592000000 # 30 days
      chatbot-verification:
        expiration: 900000 # 15 minutes
