storage:
  provider: minio # or local
  local:
    root-path: uploads

minio:
  endpoint: http://localhost:9000
  bucket-name: stonemark
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
