spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: 90000000 # 15 minutes
      refresh-token:
        expiration: 2592000000 # 30 days
    action-code:
      email-verification:
        expiration: 86400000 # 24 hours
      password-reset:
        expiration: 3600000 # 1 hour
      two-factor:
        expiration: 3600000 # 1 hour
      telephone-verification:
        expiration: 900000 # 15 minutes
      device-verification:
        expiration: 2592000000 # 30 days
      chatbot-verification:
        expiration: 900000 # 15 minutes
    contact:
      verification-required: true
