server:
  port: 8080

spring:
  profiles:
    include: chatbot, notification, file, security, processing, review
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5440/stonemark
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  jackson:
    deserializer:
      read_enum_values_using_index: false
      accept-case-insensitive-enums: true
  config:
    import: optional:file:.env[.properties]

vision:
  server:
    url: http://localhost:8000

logging:
  level:
    org.springframework: INFO
    pt.estga: DEBUG

application:
  base-url: https://api.stonemark.pt
  frontend:
    base-url: https://stonemark.pt
    auth-url: https://auth.stonemark.pt

user:
  delete-after-days: 30

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [health, info, metrics, prometheus, env]
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: [readinessState, vision, telegram, whatsapp, db]
        liveness:
          include: [livenessState]
      validate-group-membership: false
