chatbot:
  auth:
    optional: true

telegram:
  bot:
    username: stonemarkbot
    token: ${TELEGRAM_BOT_TOKEN}
    webhook-path: /webhook/telegram
    auth:
      enabled: true

whatsapp:
  bot:
    token: ${WHATSAPP_BOT_TOKEN}
    webhook-path: /webhook/whatsapp
    phone-number-id: 993756740480737
